# Generated by Django 4.2.13 on 2025-09-19 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='videos/')),
            ],
        ),
        migrations.CreateModel(
            name='Transmitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmitterSerialNumber', models.CharField(max_length=20)),
                ('nodeType', models.CharField(max_length=20)),
                ('nodeSerialNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('allCount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['transmitterSerialNumber'], name='ice_transmi_transmi_dc3eec_idx')],
            },
        ),
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceUID', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['deviceUID'], name='ice_statusl_deviceU_32ccfc_idx'), models.Index(fields=['timestamp'], name='ice_statusl_timesta_72826c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Read',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStampUTC', models.DateTimeField(auto_now_add=True)),
                ('lastTimeStamp', models.DateTimeField(null=True)),
                ('deviceUID', models.CharField(max_length=20)),
                ('manufacturerName', models.CharField(max_length=100)),
                ('distance1', models.IntegerField(blank=True, null=True)),
                ('distance2', models.IntegerField(blank=True, null=True)),
                ('distance3', models.IntegerField(blank=True, null=True)),
                ('distance4', models.IntegerField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='Out', max_length=10)),
                ('transmitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='ice.transmitter')),
            ],
            options={
                'indexes': [models.Index(fields=['deviceUID'], name='ice_read_deviceU_082606_idx'), models.Index(fields=['timeStampUTC'], name='ice_read_timeSta_626622_idx'), models.Index(fields=['deviceUID', 'timeStampUTC'], name='ice_read_deviceU_eb7ede_idx')],
            },
        ),
    ]
