# Generated by Django 4.2.13 on 2025-11-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='read',
            name='distance4',
        ),
        migrations.AlterField(
            model_name='statuslog',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
