# Generated by Django 4.2.13 on 2025-12-26 09:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ice', '0002_remove_read_distance4_alter_statuslog_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonvideo',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
