# Generated by Django 4.2.13 on 2025-12-26 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ice', '0003_commonvideo_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonvideo',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='commonvideo',
            name='log_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
