# Generated by Django 4.2.13 on 2025-12-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice', '0006_alter_commonvideo_log_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonvideo',
            name='log_date',
            field=models.DateField(),
        ),
    ]
