# Generated by Django 5.2.9 on 2026-08-31 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice', '0010_alter_commonvideo_log_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceUID', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['label'],
                'indexes': [models.Index(fields=['deviceUID'], name='ice_devicel_deviceU_d1dc59_idx')],
            },
        ),
    ]
